# 部署文档网站到 Cloudflare Pages
name: Deploy VitePress site to Cloudflare Pages

on:
  # 在推送到 main 分支时触发
  push:
    branches: [main]
  # 允许手动触发工作流
  workflow_dispatch:

# 只允许一个并发部署，跳过正在运行和最新队列之间的运行队列
# 但是，不要取消正在进行的运行，因为我们希望允许这些生产部署完成
concurrency:
  group: cloudflare-pages
  cancel-in-progress: false

jobs:
  # 构建和部署工作
  deploy:
    runs-on: ubuntu-latest
    name: Deploy to Cloudflare Pages
    env:
      CLOUDFLARE_PROJECT_NAME: ${{ secrets.CLOUDFLARE_PROJECT_NAME || 'cloudpaste-docs' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # 如果未启用 lastUpdated，则不需要

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Build with VitePress
        run: npm run docs:build

      - name: Deploy to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: ${{ env.CLOUDFLARE_PROJECT_NAME }}
          directory: docs/.vitepress/dist
          # 可选：自定义构建命令（如果需要）
          # gitHubToken: ${{ secrets.GITHUB_TOKEN }}
